;;; doom-matugen-theme.el --- A Doom theme generated by Matugen -*- lexical-binding: t; no-byte-compile: t; -*-

(require 'doom-themes)

(defgroup doom-matugen-theme nil
  "Options for the `doom-matugen' theme."
  :group 'doom-themes)

(def-doom-theme doom-matugen
  "A dark theme generated by Matugen"

  ((bg         '("#13140d" nil nil))
   (fg         '("#e4e3d7" nil nil))
   (fg-alt     '("#c7c8b7" nil nil))
   (bg-alt     '("#1b1c15" nil nil))
   (base0      '("#0e0f08" nil nil))
   (base1      '("#1b1c15" nil nil))
   (base2      '("#1f2019" nil nil))
   (base3      '("#2a2b23" nil nil))
   (base4      '("#34352d" nil nil))
   (base5      '("#919283" nil nil))
   (base6      '("#46483c" nil nil))
   (base7      '("#404c09" nil nil))
   (base8      '("#dbea98" nil nil))
   (grey       base4)
   (red        '("#ffb4ab" nil nil))
   (orange     '("#a1d0c4" nil nil))
   (green      '("#bfce7f" nil nil))
   (teal       '("#bfce7f" nil nil))
   (yellow     '("#c5c9a8" nil nil))
   (blue       '("#bfce7f" nil nil))
   (dark-blue  '("#444930" nil nil))
   (magenta    '("#a1d0c4" nil nil))
   (violet     '("#a1d0c4" nil nil))
   (cyan       '("#bfce7f" nil nil))
   (dark-cyan  '("#e1e6c3" nil nil))

   ;; Face categories
   (highlight      blue)
   (vertical-bar   base1)
   (selection      dark-blue)
   (builtin        magenta)
   (comments       base5)
   (doc-comments   base6)
   (constants      orange)
   (functions      cyan)
   (keywords       blue)
   (methods        cyan)
   (operators      blue)
   (type           yellow)
   (strings        green)
   (variables      fg)
   (numbers        orange)
   (region         selection)
   (error          red)
   (warning        yellow)
   (success        green)
   (vc-modified    orange)
   (vc-added       green)
   (vc-deleted     red))

  ;; Extra faces
  ((org-level-1 :foreground blue :weight 'bold :height 1.3)
   (org-level-2 :foreground magenta :weight 'bold :height 1.2)
   (org-level-3 :foreground green :weight 'bold :height 1.1))

  ;; Extra variables
  ()
  )

(provide-theme 'doom-matugen)
;;; doom-matugen-theme.el ends here
