;;; doom-matugen-theme.el --- A Doom theme generated by Matugen -*- lexical-binding: t; no-byte-compile: t; -*-

(require 'doom-themes)

(defgroup doom-matugen-theme nil
  "Options for the `doom-matugen' theme."
  :group 'doom-themes)

(def-doom-theme doom-matugen
  "A dark theme generated by Matugen"

  ((bg         '("#131313" nil nil))
   (fg         '("#e2e2e2" nil nil))
   (fg-alt     '("#c6c6c6" nil nil))
   (bg-alt     '("#1b1b1b" nil nil))
   (base0      '("#0e0e0e" nil nil))
   (base1      '("#1b1b1b" nil nil))
   (base2      '("#1f1f1f" nil nil))
   (base3      '("#2a2a2a" nil nil))
   (base4      '("#353535" nil nil))
   (base5      '("#919191" nil nil))
   (base6      '("#474747" nil nil))
   (base7      '("#004e5e" nil nil))
   (base8      '("#b0ecff" nil nil))
   (grey       base4)
   (red        '("#ffb4ab" nil nil))
   (orange     '("#c0c4eb" nil nil))
   (green      '("#57d6f6" nil nil))
   (teal       '("#57d6f6" nil nil))
   (yellow     '("#b2cbd3" nil nil))
   (blue       '("#57d6f6" nil nil))
   (dark-blue  '("#344a51" nil nil))
   (magenta    '("#c0c4eb" nil nil))
   (violet     '("#c0c4eb" nil nil))
   (cyan       '("#57d6f6" nil nil))
   (dark-cyan  '("#cee7ef" nil nil))

   ;; Face categories
   (highlight      blue)
   (vertical-bar   base1)
   (selection      dark-blue)
   (builtin        magenta)
   (comments       base5)
   (doc-comments   base6)
   (constants      orange)
   (functions      cyan)
   (keywords       blue)
   (methods        cyan)
   (operators      blue)
   (type           yellow)
   (strings        green)
   (variables      fg)
   (numbers        orange)
   (region         selection)
   (error          red)
   (warning        yellow)
   (success        green)
   (vc-modified    orange)
   (vc-added       green)
   (vc-deleted     red))

  ;; Extra faces
  ((org-level-1 :foreground blue :weight 'bold :height 1.3)
   (org-level-2 :foreground magenta :weight 'bold :height 1.2)
   (org-level-3 :foreground green :weight 'bold :height 1.1))

  ;; Extra variables
  ()
  )

(provide-theme 'doom-matugen)
;;; doom-matugen-theme.el ends here
