# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

# --- Fix for XWayland massive workspace number bug ---
# Electron/Chromium apps (like Vesktop/Discord) running on XWayland 
# will try to restore their window state using an X11 window ID instead of a workspace number,
# causing Hyprland to jump to a 9-digit workspace. This explicitly fences them.
windowrule = match:class ^(vesktop)$, workspace 1
windowrule = match:class ^(discord)$, workspace 1
