# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

# --- Fix for XWayland massive workspace number bug ---
# Electron/Chromium apps (like Vesktop/Discord) running on XWayland 
# will try to restore their window state using an X11 window ID instead of a workspace number,
# causing Hyprland to jump to a 9-digit workspace. This explicitly fences them.
windowrule = workspace 1, match:class ^(vesktop)$
windowrule = workspace 1, match:class ^(discord)$

# Start Motrix hidden on a special workspace
windowrule = workspace special:minimized silent, match:class ^(Motrix)$
windowrule = opacity 0.95 0.95, match:class ^(vivaldi-stable)$

