#  ┏┓┏┓┏┓┏┳┓┳┏┓┓┏  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┗┓┃┃┃┃ ┃ ┃┣ ┗┫━━┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┗┛┣┛┗┛ ┻ ┻┻ ┗┛  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#                                  


[wal]
text               = e1e2eb
subtext            = c2c6d5
main               = 11131a
main-elevated      = 11131a
main-transition    = 0b0e15
highlight          = 191b22
highlight-elevated = 191b22
sidebar            = 11131a
player             = 11131a
card               = 191b22
shadow             = 11131a
selected-row       = e1e2eb
button             = adc6ff
button-active      = d8e2ff
button-disabled    = adc6ff
tab-active         = 191b22
notification       = 11131a
notification-error = ffb4ab
misc               = 000000
play-button        = b1c6f7
play-button-active = d8e2ff
progress-fg        = adc6ff
progress-bg        = 11131a
heart              = ffb4ab
pagelink-active    = 000000
radio-btn-active   = 000000
