#  ┏┓┏┓┏┓┏┳┓┳┏┓┓┏  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┗┓┃┃┃┃ ┃ ┃┣ ┗┫━━┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┗┛┣┛┗┛ ┻ ┻┻ ┗┛  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#                                  


[wal]
text               = e2e2e2
subtext            = c6c6c6
main               = 131313
main-elevated      = 131313
main-transition    = 0e0e0e
highlight          = 1b1b1b
highlight-elevated = 1b1b1b
sidebar            = 131313
player             = 131313
card               = 1b1b1b
shadow             = 131313
selected-row       = e2e2e2
button             = f0c048
button-active      = ffdf9a
button-disabled    = f0c048
tab-active         = 1b1b1b
notification       = 131313
notification-error = ffb4ab
misc               = 000000
play-button        = d7c4a0
play-button-active = f4e0bb
progress-fg        = f0c048
progress-bg        = 131313
heart              = ffb4ab
pagelink-active    = cbebc5
radio-btn-active   = cbebc5
