;;; doom-matugen-theme.el --- A Doom theme generated by Matugen -*- lexical-binding: t; no-byte-compile: t; -*-

(require 'doom-themes)

(defgroup doom-matugen-theme nil
  "Options for the `doom-matugen' theme."
  :group 'doom-themes)

(def-doom-theme doom-matugen
  "A dark theme generated by Matugen"

  ((bg         '("{{colors.surface.default.hex}}" nil nil))
   (fg         '("{{colors.on_surface.default.hex}}" nil nil))
   (fg-alt     '("{{colors.on_surface_variant.default.hex}}" nil nil))
   (bg-alt     '("{{colors.surface_container_low.default.hex}}" nil nil))
   (base0      '("{{colors.surface_container_lowest.default.hex}}" nil nil))
   (base1      '("{{colors.surface_container_low.default.hex}}" nil nil))
   (base2      '("{{colors.surface_container.default.hex}}" nil nil))
   (base3      '("{{colors.surface_container_high.default.hex}}" nil nil))
   (base4      '("{{colors.surface_container_highest.default.hex}}" nil nil))
   (base5      '("{{colors.outline.default.hex}}" nil nil))
   (base6      '("{{colors.outline_variant.default.hex}}" nil nil))
   (base7      '("{{colors.primary_container.default.hex}}" nil nil))
   (base8      '("{{colors.on_primary_container.default.hex}}" nil nil))
   (grey       base4)
   (red        '("{{colors.error.default.hex}}" nil nil))
   (orange     '("{{colors.tertiary.default.hex}}" nil nil))
   (green      '("{{colors.primary.default.hex}}" nil nil))
   (teal       '("{{colors.primary.default.hex}}" nil nil))
   (yellow     '("{{colors.secondary.default.hex}}" nil nil))
   (blue       '("{{colors.primary.default.hex}}" nil nil))
   (dark-blue  '("{{colors.secondary_container.default.hex}}" nil nil))
   (magenta    '("{{colors.tertiary.default.hex}}" nil nil))
   (violet     '("{{colors.tertiary.default.hex}}" nil nil))
   (cyan       '("{{colors.primary.default.hex}}" nil nil))
   (dark-cyan  '("{{colors.on_secondary_container.default.hex}}" nil nil))

   ;; Face categories
   (highlight      blue)
   (vertical-bar   base1)
   (selection      dark-blue)
   (builtin        magenta)
   (comments       base5)
   (doc-comments   base6)
   (constants      orange)
   (functions      cyan)
   (keywords       blue)
   (methods        cyan)
   (operators      blue)
   (type           yellow)
   (strings        green)
   (variables      fg)
   (numbers        orange)
   (region         selection)
   (error          red)
   (warning        yellow)
   (success        green)
   (vc-modified    orange)
   (vc-added       green)
   (vc-deleted     red))

  ;; Extra faces
  ((org-level-1 :foreground blue :weight 'bold :height 1.3)
   (org-level-2 :foreground magenta :weight 'bold :height 1.2)
   (org-level-3 :foreground green :weight 'bold :height 1.1))

  ;; Extra variables
  ()
  )

(provide-theme 'doom-matugen)
;;; doom-matugen-theme.el ends here
